// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using StudentTeamPlatform.Api.Data;

#nullable disable

namespace StudentTeamPlatform.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class CreateProjectReviewsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
